<?php
/**
 * Installer API: check (public) + run (one-time).
 * The full visual wizard lives in /installer/. This mirrors the Node contract
 * so the frontend installer can call it.
 */

declare(strict_types=1);

require_once __DIR__ . '/crud.php';

/**
 * Verify a directory exists (attempt to create) and is really writable by
 * writing a probe file. The real write is the source of truth (is_writable()
 * alone can give false negatives on shared/FastCGI hosting where the FPM user
 * differs from the file owner). Returns true/false.
 */
function dir_rw(string $dir): bool
{
    if (!is_dir($dir)) {
        if (!@mkdir($dir, 0755, true) && !is_dir($dir)) return false;
    }
    $probe = rtrim($dir, '/') . '/.meb_write_probe';
    try {
        if (@file_put_contents($probe, '1') === false) return false;
        @unlink($probe);
        return true;
    } catch (\Throwable $e) {
        return false;
    }
}

/** Write DB config (host/port/name/user/pass) and app config (jwt + base_url). */
function write_install_config(string $host, int $port, string $name, string $user, string $pass, string $baseUrl = ''): void
{
    $dbc = "<?php\n/** Generated by MEB installer. */\nreturn " .
        var_export([
            'host' => $host, 'port' => $port, 'name' => $name,
            'user' => $user, 'pass' => $pass, 'charset' => 'utf8mb4',
        ], true) . ";\n";
    if (@file_put_contents(MEB_CONFIG_DIR . '/database.php', $dbc) === false) {
        throw new RuntimeException('Не удалось записать config/database.php (проверьте права на каталог config/).');
    }

    $base = normalize_site_url($baseUrl);
    $appc = "<?php\n/** Generated by MEB installer. */\nreturn " .
        var_export([
            'jwt_secret' => bin2hex(random_bytes(24)),
            'base_url'   => $base,
        ], true) . ";\n";
    if (@file_put_contents(MEB_CONFIG_DIR . '/app.php', $appc) === false) {
        throw new RuntimeException('Не удалось записать config/app.php (проверьте права на каталог config/).');
    }
}

/**
 * Normalize a user-supplied site URL.
 * - Strips trailing slashes, path segments, query, fragment
 * - Strips CRLF, tabs, null bytes (header injection protection)
 * - Validates scheme (http/https); falls back to auto-detection
 * - Returns normalized "https://host" string
 */
function normalize_site_url(string $input): string
{
    $input = preg_replace('/[\r\n\t\x00]/', '', $input);
    $input = trim($input);
    if ($input !== '') {
        $scheme = parse_url($input, PHP_URL_SCHEME);
        $host   = parse_url($input, PHP_URL_HOST);
        $input  = ($scheme !== null && $host !== null) ? ($scheme . '://' . $host) : '';
    }
    if ($input === '' || $input === '://') {
        $scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
        $hostH  = $_SERVER['HTTP_HOST'] ?? 'localhost';
        $input  = $scheme . '://' . $hostH;
    }
    return rtrim($input, '/');
}

function handle_install(string $M): void
{
    if ($M === 'GET') {
        $installed = is_file(MEB_LOCK_FILE);
        $dbOk = false;
        try {
            $dbOk = db_configured();
        } catch (\Throwable $e) {
            $dbOk = false;
        }

        $dirs = ['config' => MEB_CONFIG_DIR, 'storage' => MEB_ROOT . '/storage', 'uploads' => MEB_ROOT . '/uploads'];
        $dirResult = [];
        $allWritable = true;
        foreach ($dirs as $label => $d) {
            $dirResult[$label] = ['exists' => is_dir($d), 'writable' => dir_rw($d)];
            if (!$dirResult[$label]['writable']) $allWritable = false;
        }

        $phpOk = version_compare(PHP_VERSION, '7.1', '>=');

        // OPcache warning for shared hosting
        $warnings = [];
        if (function_exists('opcache_get_status')) {
            $opcache = @opcache_get_status(false);
            if ($opcache && !empty($opcache['opcache_enabled'])) {
                $warnings[] = 'OPcache включён. После загрузки файлов через FTP нужно перезапустить PHP-FPM или подождать автоматической инвалидации (обычно 60 сек).';
            }
        }

        ok([
            'php'     => PHP_VERSION,
            'phpOk'   => $phpOk,
            'pdo'     => extension_loaded('pdo_mysql'),
            'mysqli'  => extension_loaded('mysqli'),
            // PHP-версия не требует Node.js — отсутствие Node не является ошибкой.
            'node'    => 'не требуется',
            'storage' => $allWritable,
            'storageWritable' => $allWritable,
            'dirs'    => $dirResult,
            'requirementsOk' => $phpOk && $allWritable && extension_loaded('pdo_mysql'),
            'db'      => $dbOk,
            'version' => trim((string) @file_get_contents(MEB_ROOT . '/VERSION')),
            'installed' => $installed,
            'warnings'  => $warnings,
        ]);
    }

    if ($M === 'POST') {
        if (is_file(MEB_LOCK_FILE)) fail('Already installed', 400);
        $b = read_body();
        $email = trim((string) ($b['email'] ?? ''));
        $pass  = (string) ($b['password'] ?? '');
        if ($email === '' || $pass === '') fail('email/password required', 400);

        // Optional per-install DB credentials (7-step wizard passes them).
        // If absent, fall back to the already-written config/database.php.
        $dbName = trim((string) ($b['db_name'] ?? ''));
        $dbUser = trim((string) ($b['db_user'] ?? ''));
        $dbPass = (string) ($b['db_pass'] ?? '');
        $baseUrl = trim((string) ($b['base_url'] ?? ''));
        if ($dbName !== '' && $dbUser !== '') {
            $dbHost = trim((string) ($b['db_host'] ?? 'localhost'));
            $dbPort = (int) ($b['db_port'] ?? 3306);
            try {
                $tmp = new PDO(
                    sprintf('mysql:host=%s;port=%d;charset=utf8mb4', $dbHost, $dbPort),
                    $dbUser, $dbPass,
                    [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_TIMEOUT => 5]
                );
                $tmp->query('SELECT 1');
            } catch (\Throwable $e) {
                fail('Не удалось подключиться к MySQL: ' . $e->getMessage(), 400);
                return;
            }
            try {
                $tmp->exec('CREATE DATABASE IF NOT EXISTS `' . safe_ident($dbName) .
                            '` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
            } catch (\Throwable $e) {
                // DB may already exist, or grant may not allow CREATE — try below.
            }
            try {
                write_install_config($dbHost, $dbPort, $dbName, $dbUser, $dbPass, $baseUrl);
            } catch (\Throwable $e) {
                fail($e->getMessage(), 500);
                return;
            }
        } elseif (!is_file(MEB_CONFIG_DIR . '/database.php')) {
            fail('db_name/db_user required', 400);
            return;
        }

        try {
            handle_install_do(
                $email,
                $pass,
                (string) ($b['name'] ?? 'Admin'),
                (string) ($b['siteName'] ?? 'MEB'),
                !empty($b['demo']),
                (string) ($b['phone'] ?? '')
            );
        } catch (\Throwable $e) {
            fail($e->getMessage(), 500);
            return;
        }
        ok(true);
    }

    fail('Not found', 404);
}

/**
 * Run schema.sql against the current DB, splitting on ';' because PDO's exec()
 * cannot execute multiple statements in one call on the MySQL driver.
 * SQL line/block comments are stripped first so embedded ';' in comments do
 * not break statement splitting. Non-destructive (CREATE TABLE IF NOT EXISTS).
 * Throws on failure.
 */
function exec_schema(): void
{
    $schema = (string) @file_get_contents(MEB_ROOT . '/sql/schema.sql');
    if ($schema === '') throw new RuntimeException('schema.sql not found');

    // strip -- line comments and /* ... */ block comments (schema has no
    // string literals containing '--' or ';', so this is safe here)
    $sql = preg_replace('@/\*.*?\*/@s', '', $schema);
    $sql = preg_replace('@--[^\n]*@', '', $sql);

    $parts = array_filter(array_map('trim', explode(';', $sql)), 'strlen');
    foreach ($parts as $part) {
        if ($part === '') continue;
        db()->exec($part);
    }
}

/**
 * Perform the actual database installation: create tables, admin user,
 * default settings and optional demo seed. Shared by the HTTP API and the
 * installer wizard. Throws on failure (do not run while already installed).
 */
function handle_install_do(string $email, string $pass, string $name = 'Admin',
                           string $siteName = 'MEB', bool $demo = false,
                           string $phone = ''): void
{
    if (is_file(MEB_LOCK_FILE)) throw new RuntimeException('Already installed');

    // ensure tables exist (statement-by-statement)
    try {
        exec_schema();
    } catch (\Throwable $e) {
        throw new RuntimeException('Schema error: ' . $e->getMessage());
    }

    $id = new_id();
    $normEmail = strtolower(trim($email));
    $st = db()->prepare('INSERT INTO users (id,email,name,role,pass_hash,created_at,updated_at) VALUES (?,?,?,?,?,?,?)');
    $st->execute([$id, $normEmail, $name, 'super_admin',
                  password_hash($pass, PASSWORD_DEFAULT), now_db(), now_db()]);

    save_settings([
        'siteName' => $siteName,
        'tagline'  => 'Индивидуальная мебель',
        'phone'    => $phone,
        'email'    => $email,
    ]);

    if ($demo && is_file(MEB_ROOT . '/storage/demo-seed.json')) {
        $seed = json_decode((string) @file_get_contents(MEB_ROOT . '/storage/demo-seed.json'), true);
        if (is_array($seed)) import_seed($seed);
    }

    if (@file_put_contents(MEB_LOCK_FILE, now_iso()) === false) {
        throw new RuntimeException('Не удалось записать lock-файл ' . MEB_LOCK_FILE . ' (проверьте права на каталог storage/).');
    }
    audit_log('create', 'system', 'install');
}

/** Import demo seed arrays into MySQL (idempotent — skip existing ids). */
function import_seed(array $seed): void
{
    $map = [
        'categories' => 'catalog_categories',
        'catalog'    => 'catalog',
        'projects'   => 'projects',
        'materials'  => 'materials',
        'services'   => 'services',
        'reviews'    => 'reviews',
        'leads'      => 'requests',
        'pages'      => 'pages',
        'banners'    => 'banners',
    ];
    foreach ($map as $src => $table) {
        if (!isset($seed[$src]) || !is_array($seed[$src])) continue;
        foreach ($seed[$src] as $row) {
            if (!is_array($row)) continue;
            $id = $row['id'] ?? null;
            if ($id && find_row($table, (string) $id)) continue; // idempotent
            try {
                collection_insert_id($table, normalize_seed_row($table, $row));
            } catch (\Throwable $e) {
                // skip incompatible row
            }
        }
    }
}
